-- MySQL Script generated by MySQL Workbench
-- Mon Oct 27 10:30:48 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tools4ever
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tools4ever
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tools4ever` ;
USE `tools4ever` ;

-- -----------------------------------------------------
-- Table `tools4ever`.`locatie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tools4ever`.`locatie` (
  `locatienaam` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`locatienaam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tools4ever`.`producten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tools4ever`.`producten` (
  `type` VARCHAR(30) NOT NULL,
  `naam` VARCHAR(70) NULL DEFAULT NULL,
  `fabriek` VARCHAR(30) NULL DEFAULT NULL,
  `inkoopprijs` DECIMAL(20,2) NULL DEFAULT NULL,
  `verkoopprijs` DECIMAL(20,2) NULL DEFAULT NULL,
  PRIMARY KEY (`type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tools4ever`.`bestellingen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tools4ever`.`bestellingen` (
  `bestelnr` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(30) NOT NULL,
  `locatienaam` VARCHAR(45) NOT NULL,
  `besteldate` DATETIME NULL DEFAULT NULL,
  `aankomstdate` DATE NULL DEFAULT NULL,
  `bedrag` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`bestelnr`),
  INDEX `fk_producten_has_medewerkers_producten1_idx` (`type` ASC) VISIBLE,
  INDEX `fk_bestellingen_locatie1_idx` (`locatienaam` ASC) VISIBLE,
  CONSTRAINT `fk_bestellingen_locatie1`
    FOREIGN KEY (`locatienaam`)
    REFERENCES `tools4ever`.`locatie` (`locatienaam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producten_has_medewerkers_producten1`
    FOREIGN KEY (`type`)
    REFERENCES `tools4ever`.`producten` (`type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5;


-- -----------------------------------------------------
-- Table `tools4ever`.`locatieaantal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tools4ever`.`locatieaantal` (
  `type` VARCHAR(30) NOT NULL,
  `locatienaam` VARCHAR(45) NOT NULL,
  `aantal` DECIMAL(4,0) NULL DEFAULT NULL,
  PRIMARY KEY (`type`, `locatienaam`),
  INDEX `fk_producten_has_locatie_locatie1_idx` (`locatienaam` ASC) VISIBLE,
  INDEX `fk_producten_has_locatie_producten_idx` (`type` ASC) VISIBLE,
  CONSTRAINT `fk_producten_has_locatie_locatie1`
    FOREIGN KEY (`locatienaam`)
    REFERENCES `tools4ever`.`locatie` (`locatienaam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producten_has_locatie_producten`
    FOREIGN KEY (`type`)
    REFERENCES `tools4ever`.`producten` (`type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tools4ever`.`medewerkers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tools4ever`.`medewerkers` (
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `naam` VARCHAR(45) NULL DEFAULT NULL,
  `rol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
