-- MySQL Script generated by MySQL Workbench
-- Sat May 23 13:25:41 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`studenten`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`studenten` ;

CREATE TABLE IF NOT EXISTS `mydb`.`studenten` (
  `studentID` INT NOT NULL,
  `voornaam` VARCHAR(50) NOT NULL,
  `tussenvoegsel` VARCHAR(30) NULL,
  `achternaam` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `wachtwoord` VARCHAR(255) NOT NULL,
  `telefoon` VARCHAR(20) NOT NULL,
  `beperking` TINYINT NOT NULL,
  `omschrijving` VARCHAR(255) NULL,
  `geboortedatum` DATE NOT NULL,
  `lesUren` INT NULL,
  `lesPakket` VARCHAR(50) NULL,
  PRIMARY KEY (`studentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instructeurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`instructeurs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`instructeurs` (
  `instructeurID` INT NOT NULL,
  `voornaam` VARCHAR(50) NOT NULL,
  `tussenvoegsel` VARCHAR(30) NULL,
  `achternaam` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `wachtwoord` VARCHAR(255) NOT NULL,
  `telefoon` VARCHAR(20) NOT NULL,
  `omschrijving` VARCHAR(255) NULL,
  PRIMARY KEY (`instructeurID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Autos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Autos` (
  `autoID` INT NOT NULL,
  `merk` VARCHAR(50) NOT NULL,
  `type` VARCHAR(100) NOT NULL,
  `kenteken` VARCHAR(15) NOT NULL,
  `transmissie` TINYINT NOT NULL,
  PRIMARY KEY (`autoID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lessen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`lessen` ;

CREATE TABLE IF NOT EXISTS `mydb`.`lessen` (
  `lesID` INT NOT NULL,
  `lestijd` TIME NOT NULL,
  `ophaalLocatie` VARCHAR(100) NOT NULL,
  `doel` VARCHAR(255) NOT NULL,
  `onderwerpen` VARCHAR(255) NOT NULL,
  `studentID` INT NOT NULL,
  `instructeurID` INT NOT NULL,
  `autoID` INT NOT NULL,
  PRIMARY KEY (`lesID`),
  INDEX `fk_lessen_studenten_idx` (`studentID`),
  INDEX `fk_lessen_instructeurs1_idx` (`instructeurID`),
  INDEX `fk_lessen_Autos1_idx` (`autoID`),
  CONSTRAINT `fk_lessen_studenten`
    FOREIGN KEY (`studentID`)
    REFERENCES `mydb`.`studenten` (`studentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lessen_instructeurs1`
    FOREIGN KEY (`instructeurID`)
    REFERENCES `mydb`.`instructeurs` (`instructeurID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lessen_Autos1`
    FOREIGN KEY (`autoID`)
    REFERENCES `mydb`.`Autos` (`autoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `adminID` INT NOT NULL,
  `voornaam` VARCHAR(50) NOT NULL,
  `tussenvoegsel` VARCHAR(30) NULL,
  `achternaam` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `wachtwoord` VARCHAR(255) NOT NULL,
  `telefoon` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`adminID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`meldingen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`meldingen` ;

CREATE TABLE IF NOT EXISTS `mydb`.`meldingen` (
  `idmeldingen` INT NOT NULL,
  `tijd_melding` DATETIME NULL,
  `reden` VARCHAR(255) NULL,
  `instructeurID` INT NOT NULL,
  `lesID` INT NOT NULL,
  PRIMARY KEY (`idmeldingen`),
  INDEX `fk_meldingen_instructeurs1_idx` (`instructeurID`),
  INDEX `fk_meldingen_lessen1_idx` (`lesID`),
  CONSTRAINT `fk_meldingen_instructeurs1`
    FOREIGN KEY (`instructeurID`)
    REFERENCES `mydb`.`instructeurs` (`instructeurID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_meldingen_lessen1`
    FOREIGN KEY (`lesID`)
    REFERENCES `mydb`.`lessen` (`lesID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
